### ISSUE TITLE
Possibility to have modifier at row and cell level

### ISSUE THREAD

**Issue by sciack** [sproctor/compose-data-table#10]
Hi, 
great work porting the data-table, I had some hack before, but this implementation works well.

Just a feature nice to have and is to have modifiers at row or cell level, so for example is possible to add event on click of the row. 

In any case this library already simplify a lot my life.

**Comment by sciack** [comment]
Found the way to setup an `onClick` on each row, so I'm happy with it:
```
 row {
    onClick = {
         onClickRow(currentRow)
     }
    cell {
            ///something
   }
}
```

**Comment by sproctor** [comment]
It would be possible to add, but it seems like a bit of a clumsy API to have a modifier as an argument to a non-composable function.

Yeah, `onClick` might make more sense as a parameter. I had it as a property because it could use values from the row lambda closure. That probably isn't very interesting and it makes the API a bit more complicated to use, so maybe I'll change it for the next version.
