### ISSUE TITLE
It does not scroll !!!

### ISSUE THREAD

**Issue by SudoDios** [sproctor/compose-data-table#11]

**Comment by sproctor** [comment]
That is correct. If you want scrolling, you need to put it in a `Row` or `Column` depending on how you'd like it to scroll. The M2 spec never mentions scrolling. Here it is for reference: https://m2.material.io/components/data-tables

It supports pagination, with which you wouldn't want scrolling.

Is there some behavior that you would want that you can recreate by putting it in a scrollable `Column`?

I'm closing this because scrolling can easily be accomplished through other means. It might be interesting to implement inside DataTable after there's a lazy loading mechanism, but currently I don't see the benefit.

**Comment by eduardoleolim** [comment]
@sproctor

Could you add an example of horizontal scrolling in README?
